/*
* Form1.Designer.cs
* -------------------------------
* TestRunnerUI - Windows Forms Application (Designer Partial Class)
* 
* This partial class defines the UI components and layout for the main form (Form1)
* of the TestRunnerUI application. It is auto-generated by the Windows Forms Designer
* and includes:
* 
* - UI control declarations (Button, Label, ComboBox, RichTextBox)
* - Their initialization, positioning, sizing, and configuration
* - Event hook-ups (e.g., btnRunTests.Click)
* 
* Main UI Controls:
* - btnRunTests: Button to trigger the file dialog and start the test process
* - lblStatus: Label to display test status messages (e.g., ready, running, errors)
* - cmbFilter: Dropdown to choose output filter (all/passed/failed)
* - richTextBox1: Read-only text area for displaying the test output
* 
*/

using System;

namespace TestRunnerUI
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Button btnRunTests;
        private System.Windows.Forms.RichTextBox richTextBox1;
        private System.Windows.Forms.Label lblStatus;
        private System.Windows.Forms.ComboBox cmbFilter;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.btnRunTests = new System.Windows.Forms.Button();
            this.richTextBox1 = new System.Windows.Forms.RichTextBox();
            this.lblStatus = new System.Windows.Forms.Label();
            this.cmbFilter = new System.Windows.Forms.ComboBox();
            this.SuspendLayout();
            // 
            // btnRunTests
            // 
            this.btnRunTests.Location = new System.Drawing.Point(20, 20);
            this.btnRunTests.Name = "btnRunTests";
            this.btnRunTests.Size = new System.Drawing.Size(100, 30);
            this.btnRunTests.TabIndex = 0;
            this.btnRunTests.Text = "Run Tests";
            this.btnRunTests.UseVisualStyleBackColor = true;
            this.btnRunTests.Click += new System.EventHandler(this.btnRunTests_Click);
            // 
            // lblStatus
            // 
            this.lblStatus.AutoSize = true;
            this.lblStatus.Location = new System.Drawing.Point(140, 27);
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(104, 20);
            this.lblStatus.TabIndex = 1;
            this.lblStatus.Text = "Status: Ready";
            // 
            // cmbFilter
            // 
            this.cmbFilter.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbFilter.FormattingEnabled = true;
            this.cmbFilter.Location = new System.Drawing.Point(360, 24);
            this.cmbFilter.Name = "cmbFilter";
            this.cmbFilter.Size = new System.Drawing.Size(200, 28);
            this.cmbFilter.TabIndex = 3;
            // 
            // richTextBox1
            // 
            this.richTextBox1.Location = new System.Drawing.Point(20, 70);
            this.richTextBox1.Name = "richTextBox1";
            this.richTextBox1.ReadOnly = true;
            this.richTextBox1.Size = new System.Drawing.Size(750, 350);
            this.richTextBox1.TabIndex = 2;
            this.richTextBox1.Text = "";
            this.richTextBox1.Font = new System.Drawing.Font("Consolas", 10);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.cmbFilter);
            this.Controls.Add(this.richTextBox1);
            this.Controls.Add(this.lblStatus);
            this.Controls.Add(this.btnRunTests);
            this.Name = "Form1";
            this.Text = "Google Test Runner";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        #endregion
    }
}
